name: SEB for Windows v3.10.2 / SEB for macOS 3.7.1

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: conformance-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  conformance:
    uses: ./.github/workflows/conformance-run.yml
    with:
      windows-ref: 397f8e124387c54a9a770809003dd2e31946dcd5 # v3.10.2
      macos-ref: a1e3f786aac4aa2e827998dcf8ca139f2c5205a9 # 3.7.1
