name: SEB for Windows v3.10.2 / SEB for macOS 3.6.1

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: conformance-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  conformance:
    uses: ./.github/workflows/conformance-run.yml
    with:
      windows-ref: 397f8e124387c54a9a770809003dd2e31946dcd5 # v3.10.2
      macos-ref: 5cdbc50833e1db8c9949dfe2f65ad1853f833184 # 3.6.1
